### ISSUE TITLE
I used an error in the project and exited abnormally

### ISSUE THREAD

**Issue by esengine** [YoshihiroIto/Biaui#2]
![image](https://user-images.githubusercontent.com/18465053/74294737-cc2b6900-4d79-11ea-96e5-299a2eaf560d.png)

This is an error that occurred to me and the designer is not working properly.

Computer environment: win10
Project environment: .netframwork 4.7.2

**Comment by YoshihiroIto** [comment]
Thank you for the report.
I will fix this problem.

**Comment by YoshihiroIto** [comment]
I fixed this problem.
Please update nuget package or source code.

**Comment by esengine** [comment]
Yes, it was fixed, I closed the problem
