### ISSUE TITLE
I'd like to make a request

### ISSUE THREAD

**Issue by esengine** [YoshihiroIto/Biaui#4]
I want to have a winform-like propertygrid when I make the editor.Do you have the idea to make this control?

**Comment by YoshihiroIto** [comment]
Unfortunately, PropertyGrid is not included in the current Biaui.

I'm developing an editor at work, just like you, and I want a winform-like PropertyGrid that can be used universally.

Therefore, I've been wanting to include PropertyGrid in Biaui for some time now. I am willing to put in the time and cost for this, but it has not come to fruition.

In some of my past works I have implemented PropertyGrid. The details have been adjusted for each requirement, but they are broadly as follows

```xml
<ListBox Grid.IsSharedSizeScope="True">
  <ListBox.ItemTemplate>
    <DataTemplate>
      <Grid>
        <Grid.ColumnDefinitions>
          <ColumnDefinition SharedSizeGroup="NameColumn" />
          <ColumnDefinition SharedSizeGroup="EditControlColumn" />
        </Grid.ColumnDefinitions>

        <TextBlock Grid.Column="0" Text="{Binding Name, Mode=OneWay}" />
        <ContentControl Grid.Column="1" Content="{Binding Content, Mode=OneWay}" ContentTemplateSelector="{StaticResource PropertyGridEditControlSelector}" />
      </Grid>
    </DataTemplate>
  </ListBox.ItemTemplate>
</ListBox>

```

**Comment by esengine** [comment]
Thank you. I'll try it myself first
