### ISSUE TITLE
Buttons inside Grid do not stretch vertically

### ISSUE THREAD

**Issue by ViMaSter** [YoshihiroIto/Biaui#9]
## Problems summary
Attempting to create a button inside a grid with `VerticalAlignment="Stretch"` will center the button vertically instead.
![image](https://user-images.githubusercontent.com/1689033/102659122-260a7580-4179-11eb-8abd-75fbeb21dcf6.png)

## Expected
Identical to the default WPF behavior, the button is stretched vertically to fill the entire grid cell.
![image](https://user-images.githubusercontent.com/1689033/102659318-813c6800-4179-11eb-95c1-9e8f7f4a8003.png)

## Environment Information
* Target framework version: .NET Core 3.1
* OS: Windows 10 Pro Version	10.0.18363 Build 18363

## Provide the minimal project
https://github.com/ViMaSter/BiauiRepro

**Note:** While the project uses the default `<button>`, the same issue can be reproduced when using `<controls:BiaButton>`.

## The reproduce ways
1. Clone the repository
2. Open the MainWindow inside the designer or run the project

## Screenshot or Videocapture
_linked above_

**Comment by YoshihiroIto** [comment]
Thanks for the report.
I'll check it out.

**Comment by YoshihiroIto** [comment]
Fixed the problem.
Please update the nuget package and check it.

As for the fix, only the default height of <Button> has been changed. <BiaButton> has not been changed because it is a specialized implementation for single-line text. This is the concept of Biaui.

**Comment by ViMaSter** [comment]
That did it! I wasn't able to check it during the holidays over here in Germany!

Thank you so much for addressing the issue so quickly!
